In [1]:
import numpy as np
from sklearn.svm import SVC

In [2]:
X = np.array([[-1,-1],[-2,-1],[-2,-2],[-2,-3],[-3,-2],[1,1],[2,1],[2,2],[3,2],[2,3]])
y = np.array([1,1,1,1,1,2,2,2,2,2])

In [3]:
X

array([[-1, -1],
       [-2, -1],
       [-2, -2],
       [-2, -3],
       [-3, -2],
       [ 1,  1],
       [ 2,  1],
       [ 2,  2],
       [ 3,  2],
       [ 2,  3]])

In [4]:
y

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [5]:
clf = SVC()

In [6]:
clf.fit(X,y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [7]:
#unseen data = [-0.8,-1]
print(clf.predict([[-0.8,-1]]))

[1]


In [8]:
# get support vectors
clf.support_vectors_

array([[-1., -1.],
       [-2., -3.],
       [-3., -2.],
       [ 1.,  1.],
       [ 3.,  2.],
       [ 2.,  3.]])

In [9]:
# get indices of support vectors
clf.support_

array([0, 3, 4, 5, 8, 9], dtype=int32)

In [10]:
# get number of support vectors for each class
clf.n_support_

array([3, 3], dtype=int32)